quarkus.http.port=8081
auth.client.host=http://localhost:8080/
auth.client.accessTokenHeader=accessToken
auth.client.refreshTokenHeader=refreshToken
auth.client.accessTokenValidationUri=jwt/access-validate
auth.client.accessTokenUpdateUri=jwt/access
auth.client.loginUri=jwt/login
